version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/kyra_books
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=your-email@example.com
      - SMTP_PASS=your-password
      - SMTP_FROM=noreply@example.com
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kyra_books
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 